Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.lambda_handler
      CodeUri: /Users/chankyu/Homomimicus/dev/MIMICUS-AWStest/samTemplate/.aws-sam/build/Function
      Runtime: python3.9
      Architectures:
        - x86_64