on:
  push:
    branches:
      - main
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: IFS=$'\n'
#       - run: echo $((git diff 5988974e33cf2c62dd9023a7c64a2f82511c768f ac9909bf00a62f02aa4dedb8592d007186bcfb7c --name-only) | cut -d "/" -f1 | sort -u)
      - run: echo $((git diff 5988974e33cf2c62dd9023a7c64a2f82511c768f ac9909bf00a62f02aa4dedb8592d007186bcfb7c --name-only) | cut -d "/" -f1 | sort -u)
      - run: echo "directories=$((git diff 5988974e33cf2c62dd9023a7c64a2f82511c768f ac9909bf00a62f02aa4dedb8592d007186bcfb7c --name-only) | cut -d "/" -f1 | sort -u)" >> $GITHUB_ENV
#       - run: echo "directories=$((git diff 5988974e33cf2c62dd9023a7c64a2f82511c768f ac9909bf00a62f02aa4dedb8592d007186bcfb7c --name-only) | cut -d "/" -f1 | sort -u)" >> $GITHUB_ENV
      - run:
          echo ${{ env.directories }}
#       - id: get-directories
#         run: echo "::set-output name=directories::$(git diff ${{ github.event.before }} ${{ github.sha }} --name-only | cut -d "/" -f1 | sort -u)"
#       - run:
#           echo ${{ steps.get-directories.outputs.directories }}
#           for changed_file in ${{ steps.get-directories.outputs.directories }}
#           do
#             echo "Do something with this ${changed_file}."
#           done
#       - uses: actions/setup-python@v4
#         with:
#           python-version: "3.9"
#       - uses: aws-actions/setup-sam@v2
#       - uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-west-1
#       - run: echo 'Y' | sam sync
#           --stack-name testStack33
#           --template-file localCreationTest/template.yaml
#           --s3-bucket mimicus.dev
#           --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
#           --no-dependency-layer
