on:
  push:
    branches:
      - main
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: echo "$(git diff ${{ github.event.before }} ${{ github.sha }} --name-only | cut -d "/" -f1 | sort -u)" > directories.txt
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - run: while read directory; do [ -z "$directory" ] || [ "$directory" == .github ] && continue;
          echo 'Y' | sam sync
          --stack-name $directory
          --template-file $directory/template.yaml
          --s3-bucket mimicus.dev
          --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
          --no-dependency-layer;
          done < directories.txt
