on:
  push:
    branches:
      - main
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
#       - run: git diff ${{ github.event.before }} ${{ github.sha }}
#       - run: git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.sha }}
#       - run: git diff --name-only | cut -d "/" -f1 | sort -u
#       - run: git diff ${{ github.event.before }} ${{ github.sha }} --skip-to ".github"
      - id: get-directories
        run: git diff ${{ github.event.before }} ${{ github.sha }} --name-only | cut -d "/" -f1 | sort -u
#       - id: get-directories
#         run: echo "::set-output name=directories::git diff --name-only | cut -d "/" -f1 | sort -u"
      - run: 
          for changed_file in ${{ steps.get-directories.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done
#       - uses: actions/setup-python@v4
#         with:
#           python-version: "3.9"
#       - uses: aws-actions/setup-sam@v2
#       - uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-west-1
#       - run: echo 'Y' | sam sync
#           --stack-name testStack33
#           --template-file localCreationTest/template.yaml
#           --s3-bucket mimicus.dev
#           --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
#           --no-dependency-layer
